import type {
  Operator,
  OperatorSite,
  PricingTier,
  StaffMember,
  Vehicle,
  VehicleModel,
  AppNotification,
  OperatorReview,
  ChargingAddon,
  Booking,
} from "./types";

export const DEPOSIT_IDR = 200_000;
/** Demo starting balance: covers refundable deposit + a short typical rental. */
export const WALLET_SEED_IDR = DEPOSIT_IDR + 150_000;

/** Jakarta = primary; Bali retained as secondary. */
export const operators: Operator[] = [
  {
    id: "op-margonda",
    slug: "margonda-kost",
    name: "Casan Jakarta Hub",
    address: "3 hubs · Margonda · Tebet · Kemang",
    city: "Jakarta",
    lat: -6.3688,
    lng: 106.8322,
    hours: "06:00 - 22:00",
    phone: "+62 812-1111-2200",
    email: "hello@margondakost.id",
    supportsFrontDesk: true,
    supportsSelfService: true,
    shopPickupLabel: "Kost lobby counter · Margonda",
    selfCollectLabel: "Basement rack B2 · QR unlock",
    selfCollectLat: -6.3692,
    selfCollectLng: 106.8328,
    platformFeePct: 15,
    emoji: "🏙",
    coverImage: "/vehicles/ofero-galaxy3-1.jpg",
    locationImages: [
      "/locations/margonda-kost.svg",
      "/locations/casan-hub.svg",
      "/locations/tebet-lobby.svg",
    ],
    mapImage: "/maps/margonda.svg",
  },
  {
    id: "op-tebet",
    slug: "tebet-student",
    name: "Tebet Student Wheels",
    address: "Jl. Tebet Barat Dalam VIII, Jakarta Selatan",
    city: "Jakarta",
    lat: -6.2267,
    lng: 106.8475,
    hours: "07:00 - 21:00",
    phone: "+62 812-2222-4400",
    email: "desk@tebetwheels.id",
    supportsFrontDesk: true,
    supportsSelfService: true,
    shopPickupLabel: "Tebet kost center desk",
    selfCollectLabel: "Side alley pin · self-collect",
    selfCollectLat: -6.2271,
    selfCollectLng: 106.848,
    platformFeePct: 16,
    emoji: "🏠",
    coverImage: "/vehicles/ofero-stareer3-1.jpg",
    locationImages: [
      "/locations/tebet-lobby.svg",
      "/locations/casan-hub.svg",
      "/locations/margonda-kost.svg",
    ],
    mapImage: "/maps/tebet.svg",
  },
  {
    id: "op-rawamangun",
    slug: "rawamangun-unj",
    name: "Rawamangun Campus Ride",
    address: "Jl. Pemuda No. 10, Rawamangun",
    city: "Jakarta",
    lat: -6.1944,
    lng: 106.8833,
    hours: "06:30 - 21:30",
    phone: "+62 812-3333-5500",
    email: "ride@rawacampus.id",
    supportsFrontDesk: true,
    supportsSelfService: true,
    shopPickupLabel: "UNJ-side counter",
    selfCollectLabel: "Campus rack · app unlock 24h",
    selfCollectLat: -6.1948,
    selfCollectLng: 106.8838,
    platformFeePct: 14,
    emoji: "🎓",
    coverImage: "/vehicles/uwinfly-m110g.jpg",
    locationImages: [
      "/locations/rawamangun-rack.svg",
      "/locations/casan-hub.svg",
      "/locations/margonda-kost.svg",
    ],
    mapImage: "/maps/rawamangun.svg",
  },
  {
    id: "op-bali-sunset",
    slug: "bali-sunset",
    name: "Bali Sunset Hotel",
    address: "Jl. Pantai Kuta No. 42, Kuta",
    city: "Bali",
    lat: -8.7177,
    lng: 115.1708,
    hours: "07:00 - 20:00",
    phone: "+62 812-3456-7890",
    email: "rental@balisunset.com",
    supportsFrontDesk: true,
    supportsSelfService: true,
    shopPickupLabel: "Hotel front desk · Kuta lobby",
    selfCollectLabel: "Lot B · unmanned dock (QR unlock)",
    selfCollectLat: -8.7179,
    selfCollectLng: 115.1712,
    platformFeePct: 20,
    emoji: "🏨",
    coverImage: "/vehicles/uwinfly-banner.jpg",
    locationImages: ["/vehicles/uwinfly-banner.jpg", "/locations/casan-hub.svg"],
    mapImage: "/maps/kuta.svg",
  },
  {
    id: "op-beachwalk",
    slug: "beachwalk",
    name: "BeachWalk Rental Hub",
    address: "Jl. Pantai Berawa, Canggu",
    city: "Bali",
    lat: -8.6595,
    lng: 115.1303,
    hours: "06:30 - 21:00",
    phone: "+62 812-2222-3333",
    email: "hello@beachwalk.id",
    supportsFrontDesk: false,
    supportsSelfService: true,
    shopPickupLabel: "Hub counter (when staffed)",
    selfCollectLabel: "Berawa pin · self-collect, no staff needed",
    selfCollectLat: -8.6597,
    selfCollectLng: 115.1306,
    platformFeePct: 18,
    emoji: "🏛",
    coverImage: "/vehicles/ofero-galaxy3-1.jpg",
    locationImages: [
      "/vehicles/ofero-galaxy3-1.jpg",
      "/locations/casan-hub.svg",
    ],
    mapImage: "/maps/canggu.svg",
  },
  {
    id: "op-ubud",
    slug: "ubud-center",
    name: "Ubud Tourism Center",
    address: "Jl. Raya Ubud No. 18",
    city: "Bali",
    lat: -8.5069,
    lng: 115.2625,
    hours: "08:00 - 18:00",
    phone: "+62 812-8888-1111",
    email: "desk@ubudcenter.id",
    supportsFrontDesk: true,
    supportsSelfService: false,
    shopPickupLabel: "Tourism center counter",
    selfCollectLabel: "—",
    selfCollectLat: -8.5069,
    selfCollectLng: 115.2625,
    platformFeePct: 22,
    emoji: "🏫",
    coverImage: "/vehicles/ofero-ledo3-1.jpg",
    locationImages: ["/vehicles/ofero-ledo3-1.jpg", "/locations/casan-hub.svg"],
    mapImage: "/maps/ubud.svg",
  },
];

export const operatorSites: OperatorSite[] = (
  [
  {
    id: "site-margonda-lobby",
    operatorId: "op-margonda",
    name: "Margonda Kost Lobby",
    area: "Depok / Margonda",
    address: "Jl. Margonda Raya No. 358, Beji, Depok — lobby counter next to 7-Eleven",
    lat: -6.3688,
    lng: 106.8322,
    hours: "06:00 - 22:00",
    opensAt: "06:00",
    closesAt: "22:00",
    whatsapp: "+62 812-1111-2200",
    mapImage: "/maps/margonda.svg",
    storeInfo:
      "Pickup at lobby. Helmets in the blue cabinet. Tell staff your booking code. Return bikes to the yellow rack.",
    supportsFrontDesk: true,
    supportsSelfService: false,
    shopPickupLabel: "Kost lobby counter · Margonda",
    selfCollectLabel: "—",
  },
  {
    id: "site-jakarta-tebet",
    operatorId: "op-margonda",
    name: "Tebet Hub",
    area: "Tebet",
    address: "Jl. Tebet Barat Dalam VIII No. 12, Jakarta Selatan — kost center desk",
    lat: -6.2267,
    lng: 106.8475,
    hours: "07:00 - 21:00",
    opensAt: "07:00",
    closesAt: "21:00",
    whatsapp: "+62 812-1111-3300",
    mapImage: "/maps/tebet.svg",
    storeInfo:
      "Side alley entrance. Physical keys hung on board A. Self-collect pin is 40m south for digital unlocks.",
    supportsFrontDesk: true,
    supportsSelfService: true,
    shopPickupLabel: "Tebet kost desk · hand key",
    selfCollectLabel: "Alley pin · self-collect",
  },
  {
    id: "site-jakarta-kemang",
    operatorId: "op-margonda",
    name: "Kemang Corner",
    area: "Kemang",
    address: "Jl. Kemang Raya No. 15, Jakarta Selatan — student kost row corner shop",
    lat: -6.2612,
    lng: 106.8128,
    hours: "07:00 - 22:00",
    opensAt: "07:00",
    closesAt: "22:00",
    whatsapp: "+62 812-1111-4400",
    mapImage: "/maps/tebet.svg",
    storeInfo:
      "Corner shop with glass front. Charging adapters in drawer 2. Closed Fridays 12:00–13:00 for sholat.",
    supportsFrontDesk: true,
    supportsSelfService: false,
    shopPickupLabel: "Kemang corner desk",
    selfCollectLabel: "—",
  },
  // Secondary operators keep one hub each for multi-city discovery
  {
    id: "site-tebet-desk",
    operatorId: "op-tebet",
    name: "Tebet Student Desk",
    area: "Tebet",
    address: "Jl. Tebet Barat Dalam VIII, Jakarta Selatan",
    lat: -6.2267,
    lng: 106.8475,
    hours: "07:00 - 21:00",
    opensAt: "07:00",
    closesAt: "21:00",
    whatsapp: "+62 812-2222-4400",
    mapImage: "/maps/tebet.svg",
    storeInfo: "Independent Tebet operator desk — not Casan Jakarta Hub.",
    supportsFrontDesk: true,
    supportsSelfService: true,
    shopPickupLabel: "Tebet kost center desk",
    selfCollectLabel: "Side alley pin · self-collect",
  },
  {
    id: "site-rawa-counter",
    operatorId: "op-rawamangun",
    name: "Rawamangun UNJ Counter",
    area: "Rawamangun",
    address: "Jl. Pemuda No. 10, Rawamangun · UNJ corridor",
    lat: -6.1944,
    lng: 106.8833,
    hours: "06:30 - 21:30",
    opensAt: "06:30",
    closesAt: "21:30",
    whatsapp: "+62 812-3333-5500",
    mapImage: "/maps/rawamangun.svg",
    storeInfo: "Campus counter facing UNJ gate 2.",
    supportsFrontDesk: true,
    supportsSelfService: true,
    shopPickupLabel: "UNJ-side counter",
    selfCollectLabel: "Campus rack · app unlock 24h",
  },
  {
    id: "site-bali-lobby",
    operatorId: "op-bali-sunset",
    name: "Bali Sunset Lobby",
    area: "Kuta",
    address: "Jl. Pantai Kuta No. 42, Kuta",
    lat: -8.7177,
    lng: 115.1708,
    hours: "07:00 - 20:00",
    opensAt: "07:00",
    closesAt: "20:00",
    whatsapp: "+62 812-3456-7890",
    mapImage: "/maps/kuta.svg",
    storeInfo: "Hotel front desk — ask for Casan rental keys.",
    supportsFrontDesk: true,
    supportsSelfService: true,
    shopPickupLabel: "Hotel front desk · Kuta lobby",
    selfCollectLabel: "Lot B · unmanned dock",
  },
  {
    id: "site-beach-hub",
    operatorId: "op-beachwalk",
    name: "BeachWalk Berawa Hub",
    area: "Canggu",
    address: "Jl. Pantai Berawa, Canggu",
    lat: -8.6595,
    lng: 115.1303,
    hours: "06:30 - 21:00",
    opensAt: "06:30",
    closesAt: "21:00",
    whatsapp: "+62 812-2222-3333",
    mapImage: "/maps/canggu.svg",
    storeInfo: "Self-collect first; staff on weekends only.",
    supportsFrontDesk: false,
    supportsSelfService: true,
    shopPickupLabel: "Hub counter (when staffed)",
    selfCollectLabel: "Berawa pin · self-collect",
  },
  {
    id: "site-ubud-desk",
    operatorId: "op-ubud",
    name: "Ubud Tourism Desk",
    area: "Ubud",
    address: "Jl. Raya Ubud No. 18",
    lat: -8.5069,
    lng: 115.2625,
    hours: "08:00 - 18:00",
    opensAt: "08:00",
    closesAt: "18:00",
    whatsapp: "+62 812-8888-1111",
    mapImage: "/maps/ubud.svg",
    storeInfo: "Tourism center counter — physical key only.",
    supportsFrontDesk: true,
    supportsSelfService: false,
    shopPickupLabel: "Tourism center counter",
    selfCollectLabel: "—",
  },
]
).map((s) => ({
  ...s,
  city:
    operators.find((o) => o.id === s.operatorId)?.city ??
    "Jakarta",
  area: s.area ?? s.name,
}));

/**
 * Charging SKUs for kost students:
 * - Casan vouchers: redeem at hub charge bays
 * - Adapters: voltage MUST match pack; A = charge speed (2–3A kost-safe, 5A upsell)
 */
export const chargingAddons: ChargingAddon[] = [
  {
    id: "addon-voucher-1",
    kind: "casan_voucher",
    label: "Casan overnight ×1",
    description: "1 overnight charge slot at any Casan hub near your kost.",
    priceIdr: 25_000,
    voucherSlots: 1,
    forVoltageV: null,
  },
  {
    id: "addon-voucher-3",
    kind: "casan_voucher",
    label: "Casan overnight ×3",
    description: "Student pack — 3 overnight slots. Best for weekly campus commute.",
    priceIdr: 65_000,
    voucherSlots: 3,
    forVoltageV: null,
  },
  {
    id: "addon-voucher-7",
    kind: "casan_voucher",
    label: "Casan 7-day student",
    description: "Unlimited overnight slots for 7 days at Casan hubs (fair-use).",
    priceIdr: 120_000,
    voucherSlots: 7,
    forVoltageV: null,
  },
  {
    id: "addon-adapter-48-2",
    kind: "adapter",
    label: "Include 48V · 2A adapter",
    description: "Kost-safe overnight charge (~5–8h for 12–15Ah). Matches 48V packs only.",
    priceIdr: 35_000,
    amps: 2,
    forVoltageV: 48,
  },
  {
    id: "addon-adapter-48-3",
    kind: "adapter",
    label: "Include 48V · 3A adapter",
    description: "Faster overnight (~3–5h). Still gentle on 900–1300 VA kost circuits.",
    priceIdr: 45_000,
    amps: 3,
    forVoltageV: 48,
  },
  {
    id: "addon-adapter-60-3",
    kind: "adapter",
    label: "Include 60V · 3A adapter",
    description: "Default for 60V mid mopeds. Warn: do not use on 48V packs.",
    priceIdr: 50_000,
    amps: 3,
    forVoltageV: 60,
  },
  {
    id: "addon-adapter-72-3",
    kind: "adapter",
    label: "Include 72V · 3A adapter",
    description: "Kost-safe for 72V packs. High-V chargers must match voltage exactly.",
    priceIdr: 55_000,
    amps: 3,
    forVoltageV: 72,
  },
  {
    id: "addon-adapter-72-5",
    kind: "adapter",
    label: "Upgrade 72V · 5A (fast)",
    description: "Daytime / hub use. May trip shared kost outlets (900 VA) — use Casan bay if unsure.",
    priceIdr: 75_000,
    amps: 5,
    forVoltageV: 72,
  },
  {
    id: "addon-adapter-60-5",
    kind: "adapter",
    label: "Upgrade 60V · 5A (fast)",
    description: "Faster charge; prefer Casan hub or dedicated outlet, not weak kost circuits.",
    priceIdr: 70_000,
    amps: 5,
    forVoltageV: 60,
  },
];

/** Demo photos from Ofero & Uwinfly — battery V/Ah for kost students. */
export const vehicleModels: VehicleModel[] = [
  {
    id: "m-margo-galaxy",
    operatorId: "op-margonda",
    name: "Ofero Galaxy 3 Lit",
    vehicleType: "ebike",
    description:
      "48V city e-bike for UI ↔ kost. Includes helmet; add Casan voucher or 2A adapter for overnight charge.",
    images: [
      "/vehicles/ofero-galaxy3-1.jpg",
      "/vehicles/ofero-galaxy3-2.jpg",
      "/vehicles/ofero-galaxy2-1.jpg",
    ],
    pricePerHour: 35_000,
    rentalMode: "both",
    allowFrontDesk: true,
    allowSelfService: true,
    motorWatts: 250,
    rangeKm: 60,
    maxSpeedKmh: 25,
    weightKg: 22,
    batteryVoltageV: 48,
    batteryAh: 12,
    chargerAmpsDefault: 2,
    requiresSimAck: false,
    emoji: "🚲",
    includes: ["Helmet", "U-lock", "48V·2A adapter option"],
  },
  {
    id: "m-margo-ledo",
    operatorId: "op-margonda",
    name: "Kost City Pedal",
    vehicleType: "bicycle",
    description:
      "Classic pedal bike for short kost ↔ warung trips. No battery. Physical key only — collect & return at shop.",
    images: ["/vehicles/ofero-ledo3-1.jpg", "/vehicles/ofero-ledo3-2.jpg"],
    pricePerHour: 15_000,
    rentalMode: "key_handover",
    allowFrontDesk: true,
    allowSelfService: false,
    motorWatts: null,
    rangeKm: null,
    maxSpeedKmh: null,
    weightKg: 14,
    batteryVoltageV: null,
    batteryAh: null,
    chargerAmpsDefault: null,
    requiresSimAck: false,
    emoji: "🚲",
    includes: ["Basket", "Bell", "Physical key", "U-lock"],
  },
  {
    id: "m-margo-m110",
    operatorId: "op-margonda",
    name: "Uwinfly M110G",
    vehicleType: "emoped",
    description:
      "72V·32Ah performance moped. Indonesian SIM required. Prefer 3A adapter or Casan hub — 5A trips weak kost circuits.",
    images: [
      "/vehicles/uwinfly-m110g.jpg",
      "/vehicles/uwinfly-banner.jpg",
      "/vehicles/uwinfly-product2.png",
    ],
    pricePerHour: 65_000,
    rentalMode: "both",
    allowFrontDesk: true,
    allowSelfService: true,
    motorWatts: 3000,
    rangeKm: 100,
    maxSpeedKmh: 85,
    weightKg: 95,
    batteryVoltageV: 72,
    batteryAh: 32,
    chargerAmpsDefault: 3,
    requiresSimAck: true,
    emoji: "🛵",
    includes: ["2× Helmet", "Phone holder", "Rain cover"],
  },
  {
    id: "m-tebet-magical",
    operatorId: "op-tebet",
    name: "Tebet Campus Pedal",
    vehicleType: "bicycle",
    description:
      "Simple pedal bike near komuter. No battery pack. Physical shop key only — operator gives & collects the key.",
    images: [
      "/vehicles/ofero-magical3-1.jpg",
      "/vehicles/ofero-magical3-2.jpg",
    ],
    pricePerHour: 12_000,
    rentalMode: "key_handover",
    allowFrontDesk: true,
    allowSelfService: false,
    motorWatts: null,
    rangeKm: null,
    maxSpeedKmh: null,
    weightKg: 13,
    batteryVoltageV: null,
    batteryAh: null,
    chargerAmpsDefault: null,
    requiresSimAck: false,
    emoji: "🚲",
    includes: ["Cable lock", "Physical key", "Bell"],
  },
  {
    id: "m-tebet-stareer",
    operatorId: "op-tebet",
    name: "Ofero Stareer 3 Lit",
    vehicleType: "emoped",
    description:
      "60V·20Ah mid moped. Include 3A adapter for kost overnight; 5A only if you have a strong outlet.",
    images: [
      "/vehicles/ofero-stareer3-1.jpg",
      "/vehicles/ofero-stareer3-2.jpg",
      "/vehicles/ofero-stareer-motor-1.jpg",
    ],
    pricePerHour: 55_000,
    rentalMode: "both",
    allowFrontDesk: true,
    allowSelfService: true,
    motorWatts: 1200,
    rangeKm: 55,
    maxSpeedKmh: 42,
    weightKg: 65,
    batteryVoltageV: 60,
    batteryAh: 20,
    chargerAmpsDefault: 3,
    requiresSimAck: true,
    emoji: "🛵",
    includes: ["Helmet", "Under-seat storage"],
  },
  {
    id: "m-rawa-city",
    operatorId: "op-rawamangun",
    name: "UNJ Pedal Classic",
    vehicleType: "bicycle",
    description:
      "Pedal-only bike for UNJ campus. No battery. Physical key at counter only.",
    images: [
      "/vehicles/uwinfly-product1.png",
      "/vehicles/uwinfly-product3.png",
    ],
    pricePerHour: 10_000,
    rentalMode: "key_handover",
    allowFrontDesk: true,
    allowSelfService: false,
    motorWatts: null,
    rangeKm: null,
    maxSpeedKmh: null,
    weightKg: 12,
    batteryVoltageV: null,
    batteryAh: null,
    chargerAmpsDefault: null,
    requiresSimAck: false,
    emoji: "🚲",
    includes: ["Physical key", "Map card", "Bell"],
  },
  {
    id: "m-rawa-picassio",
    operatorId: "op-rawamangun",
    name: "Ofero Picassio",
    vehicleType: "emoped",
    description:
      "72V·20Ah for longer east-Jakarta hops. Adapter must be 72V — wrong voltage damages the pack.",
    images: ["/vehicles/ofero-picassio-1.png"],
    pricePerHour: 70_000,
    rentalMode: "key_handover",
    allowFrontDesk: true,
    allowSelfService: false,
    motorWatts: 2000,
    rangeKm: 80,
    maxSpeedKmh: 60,
    weightKg: 90,
    batteryVoltageV: 72,
    batteryAh: 20,
    chargerAmpsDefault: 3,
    requiresSimAck: true,
    emoji: "🛵",
    includes: ["2× Helmet", "Lock"],
  },
  // Bali secondary
  {
    id: "m-eco-cruiser",
    operatorId: "op-bali-sunset",
    name: "Ofero Galaxy 3 Lit",
    vehicleType: "ebike",
    description:
      "Ofero Galaxy 3 Lit city e-bike (Bali). 48V·12Ah. Demo photos from ofero.id.",
    images: [
      "/vehicles/ofero-galaxy3-1.jpg",
      "/vehicles/ofero-galaxy3-2.jpg",
      "/vehicles/ofero-galaxy2-1.jpg",
    ],
    pricePerHour: 50_000,
    rentalMode: "both",
    allowFrontDesk: true,
    allowSelfService: true,
    motorWatts: 250,
    rangeKm: 60,
    maxSpeedKmh: 25,
    weightKg: 22,
    batteryVoltageV: 48,
    batteryAh: 12,
    chargerAmpsDefault: 2,
    requiresSimAck: false,
    emoji: "🚲",
    includes: ["Helmet", "U-lock", "Phone mount"],
  },
  {
    id: "m-swift-moped",
    operatorId: "op-bali-sunset",
    name: "Uwinfly M110G",
    vehicleType: "emoped",
    description:
      "Uwinfly M110G (Bali). 72V·32Ah. Indonesian SIM required.",
    images: [
      "/vehicles/uwinfly-m110g.jpg",
      "/vehicles/uwinfly-banner.jpg",
      "/vehicles/uwinfly-product2.png",
    ],
    pricePerHour: 75_000,
    rentalMode: "both",
    allowFrontDesk: true,
    allowSelfService: true,
    motorWatts: 3000,
    rangeKm: 100,
    maxSpeedKmh: 85,
    weightKg: 95,
    batteryVoltageV: 72,
    batteryAh: 32,
    chargerAmpsDefault: 3,
    requiresSimAck: true,
    emoji: "🛵",
    includes: ["2× Helmet", "Phone holder", "Rain cover"],
  },
  {
    id: "m-city-x1",
    operatorId: "op-beachwalk",
    name: "Ofero Magical 3 Lit",
    vehicleType: "ebike",
    description: "Ofero Magical 3 Lit · Canggu. 48V·15Ah.",
    images: [
      "/vehicles/ofero-magical3-1.jpg",
      "/vehicles/ofero-magical3-2.jpg",
    ],
    pricePerHour: 40_000,
    rentalMode: "digital",
    allowFrontDesk: false,
    allowSelfService: true,
    motorWatts: 350,
    rangeKm: 80,
    maxSpeedKmh: 28,
    weightKg: 24,
    batteryVoltageV: 48,
    batteryAh: 15,
    chargerAmpsDefault: 2,
    requiresSimAck: false,
    emoji: "🚴",
    includes: ["Helmet", "Cable lock"],
  },
  {
    id: "m-canggu-moped",
    operatorId: "op-beachwalk",
    name: "Ofero Stareer 3 Lit",
    vehicleType: "emoped",
    description: "Ofero Stareer 3 Lit · Canggu. 60V·20Ah.",
    images: [
      "/vehicles/ofero-stareer3-1.jpg",
      "/vehicles/ofero-stareer3-2.jpg",
      "/vehicles/ofero-stareer-motor-1.jpg",
    ],
    pricePerHour: 65_000,
    rentalMode: "digital",
    allowFrontDesk: false,
    allowSelfService: true,
    motorWatts: 1200,
    rangeKm: 55,
    maxSpeedKmh: 42,
    weightKg: 65,
    batteryVoltageV: 60,
    batteryAh: 20,
    chargerAmpsDefault: 3,
    requiresSimAck: true,
    emoji: "🛵",
    includes: ["Helmet", "Under-seat storage"],
  },
  {
    id: "m-beach-lite",
    operatorId: "op-beachwalk",
    name: "Beach Pedal Lite",
    vehicleType: "bicycle",
    description: "Pedal bike for beach loops. No battery. Physical key only.",
    images: ["/vehicles/ofero-ledo3-1.jpg", "/vehicles/ofero-ledo3-2.jpg"],
    pricePerHour: 20_000,
    rentalMode: "key_handover",
    allowFrontDesk: true,
    allowSelfService: false,
    motorWatts: null,
    rangeKm: null,
    maxSpeedKmh: null,
    weightKg: 14,
    batteryVoltageV: null,
    batteryAh: null,
    chargerAmpsDefault: null,
    requiresSimAck: false,
    emoji: "🚲",
    includes: ["Basket", "Bell", "Physical key"],
  },
  {
    id: "m-rice-terrace",
    operatorId: "op-ubud",
    name: "Uwinfly City Ride",
    vehicleType: "ebike",
    description: "Uwinfly e-bike · Ubud. 48V·12Ah.",
    images: [
      "/vehicles/uwinfly-product1.png",
      "/vehicles/uwinfly-product3.png",
    ],
    pricePerHour: 30_000,
    rentalMode: "key_handover",
    allowFrontDesk: true,
    allowSelfService: false,
    motorWatts: 350,
    rangeKm: 50,
    maxSpeedKmh: 25,
    weightKg: 22,
    batteryVoltageV: 48,
    batteryAh: 12,
    chargerAmpsDefault: 2,
    requiresSimAck: false,
    emoji: "🚲",
    includes: ["Helmet", "Map card"],
  },
  {
    id: "m-temple-assist",
    operatorId: "op-ubud",
    name: "Ofero Picassio",
    vehicleType: "emoped",
    description: "Ofero Picassio · Ubud hills. 72V·20Ah.",
    images: ["/vehicles/ofero-picassio-1.png"],
    pricePerHour: 85_000,
    rentalMode: "key_handover",
    allowFrontDesk: true,
    allowSelfService: false,
    motorWatts: 2000,
    rangeKm: 80,
    maxSpeedKmh: 60,
    weightKg: 90,
    batteryVoltageV: 72,
    batteryAh: 20,
    chargerAmpsDefault: 3,
    requiresSimAck: true,
    emoji: "🛵",
    includes: ["2× Helmet", "Lock"],
  },
];

function unit(
  partial: Omit<
    Vehicle,
    | "name"
    | "vehicleType"
    | "rentalMode"
    | "allowFrontDesk"
    | "allowSelfService"
    | "motorWatts"
    | "rangeKm"
    | "maxSpeedKmh"
    | "weightKg"
    | "batteryVoltageV"
    | "batteryAh"
    | "chargerAmpsDefault"
    | "pricePerHour"
    | "emoji"
    | "requiresSimAck"
    | "color"
    | "colorHex"
  > & { modelId: string; batteryPct?: number | null; color?: string; colorHex?: string },
): Vehicle {
  const model = vehicleModels.find((m) => m.id === partial.modelId)!;
  const isBike = model.vehicleType === "bicycle";
  const palette = FLEET_COLORS;
  const tone = palette[Math.abs(hashCode(partial.code)) % palette.length];
  return {
    ...partial,
    name: model.name,
    vehicleType: model.vehicleType,
    rentalMode: model.rentalMode,
    allowFrontDesk: model.allowFrontDesk,
    allowSelfService: model.allowSelfService,
    motorWatts: model.motorWatts,
    rangeKm: model.rangeKm,
    maxSpeedKmh: model.maxSpeedKmh,
    weightKg: model.weightKg,
    batteryVoltageV: model.batteryVoltageV,
    batteryAh: model.batteryAh,
    chargerAmpsDefault: model.chargerAmpsDefault,
    batteryPct: isBike ? null : (partial.batteryPct ?? 80),
    pricePerHour: model.pricePerHour,
    emoji: model.emoji,
    requiresSimAck: model.requiresSimAck,
    color: partial.color ?? tone.color,
    colorHex: partial.colorHex ?? tone.colorHex,
  };
}

function hashCode(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return h;
}

const FLEET_COLORS = [
  { color: "Black", colorHex: "#1C1C1E" },
  { color: "White", colorHex: "#F2F2F7" },
  { color: "Teal", colorHex: "#0D9488" },
  { color: "Navy", colorHex: "#1E3A5F" },
  { color: "Red", colorHex: "#C0392B" },
  { color: "Silver", colorHex: "#A8B0B8" },
  { color: "Forest", colorHex: "#1B5E3B" },
  { color: "Sand", colorHex: "#C4A574" },
];


/** Build 10–15 demo units for one hub. Keeps legacy mock booking vehicle ids. */
function buildSiteFleet(opts: {
  siteId: string;
  operatorId: string;
  lat: number;
  lng: number;
  idPrefix: string;
  units: { modelId: string; codePrefix: string; count: number; start: number }[];
}): Vehicle[] {
  const out: Vehicle[] = [];
  const batts = [94, 88, 81, 76, 72, 68, 91, 85, 79, 73, 96, 84];
  let bi = 0;
  for (const group of opts.units) {
    for (let i = 0; i < group.count; i++) {
      const n = group.start + i;
      const codeNum = String(n).padStart(2, "0");
      const short = group.codePrefix.split("-").pop()!.toLowerCase();
      let id = `v-${opts.idPrefix}-${short}${n}`;
      if (opts.siteId === "site-margonda-lobby" && group.modelId === "m-margo-galaxy" && n === 1) {
        id = "v-mg-g1";
      }
      if (opts.siteId === "site-jakarta-tebet" && group.modelId === "m-margo-ledo" && n === 1) {
        id = "v-mg-l1";
      }
      if (opts.siteId === "site-margonda-lobby" && group.modelId === "m-margo-m110" && n === 1) {
        id = "v-mg-m1";
      }
      out.push(
        unit({
          id,
          modelId: group.modelId,
          operatorId: opts.operatorId,
          siteId: opts.siteId,
          code: `${group.codePrefix}${codeNum}`,
          status: "available",
          batteryPct: batts[bi++ % batts.length],
          lat: opts.lat + (i % 3) * 0.0001,
          lng: opts.lng + (i % 2) * 0.0001,
        }),
      );
    }
  }
  return out;
}

export const vehicles: Vehicle[] = [
  // --- Casan Jakarta Hub: 12 bikes × 3 locations ---
  ...buildSiteFleet({
    siteId: "site-margonda-lobby",
    operatorId: "op-margonda",
    lat: -6.3688,
    lng: 106.8322,
    idPrefix: "mg",
    units: [
      { modelId: "m-margo-galaxy", codePrefix: "MG-E", count: 5, start: 1 },
      { modelId: "m-margo-ledo", codePrefix: "MG-L", count: 3, start: 1 },
      { modelId: "m-margo-m110", codePrefix: "MG-M", count: 4, start: 1 },
    ],
  }),
  ...buildSiteFleet({
    siteId: "site-jakarta-tebet",
    operatorId: "op-margonda",
    lat: -6.2267,
    lng: 106.8475,
    idPrefix: "jt",
    units: [
      { modelId: "m-margo-galaxy", codePrefix: "TB-E", count: 5, start: 1 },
      { modelId: "m-margo-ledo", codePrefix: "TB-L", count: 4, start: 1 },
      { modelId: "m-margo-m110", codePrefix: "TB-M", count: 3, start: 1 },
    ],
  }),
  ...buildSiteFleet({
    siteId: "site-jakarta-kemang",
    operatorId: "op-margonda",
    lat: -6.2612,
    lng: 106.8128,
    idPrefix: "km",
    units: [
      { modelId: "m-margo-galaxy", codePrefix: "KM-E", count: 4, start: 1 },
      { modelId: "m-margo-ledo", codePrefix: "KM-L", count: 4, start: 1 },
      { modelId: "m-margo-m110", codePrefix: "KM-M", count: 4, start: 1 },
    ],
  }),
  // Secondary operators — small demo fleets
  unit({
    id: "v-tb-m1",
    modelId: "m-tebet-magical",
    operatorId: "op-tebet",
    siteId: "site-tebet-desk",
    code: "TW-L01",
    status: "available",
    batteryPct: null,
    lat: -6.2267,
    lng: 106.8475,
  }),
  unit({
    id: "v-tb-s1",
    modelId: "m-tebet-stareer",
    operatorId: "op-tebet",
    siteId: "site-tebet-desk",
    code: "TW-E01",
    status: "available",
    batteryPct: 88,
    lat: -6.2268,
    lng: 106.8476,
  }),
  unit({
    id: "v-rw-c1",
    modelId: "m-rawa-city",
    operatorId: "op-rawamangun",
    siteId: "site-rawa-counter",
    code: "RW-L01",
    status: "available",
    batteryPct: null,
    lat: -6.1944,
    lng: 106.8833,
  }),
  unit({
    id: "v-rw-p1",
    modelId: "m-rawa-picassio",
    operatorId: "op-rawamangun",
    siteId: "site-rawa-counter",
    code: "RW-E01",
    status: "available",
    batteryPct: 79,
    lat: -6.1945,
    lng: 106.8834,
  }),
  unit({
    id: "v-bs-01",
    modelId: "m-eco-cruiser",
    operatorId: "op-bali-sunset",
    siteId: "site-bali-lobby",
    code: "BS-E01",
    status: "available",
    batteryPct: 90,
    lat: -8.7177,
    lng: 115.1708,
  }),
  unit({
    id: "v-bs-02",
    modelId: "m-swift-moped",
    operatorId: "op-bali-sunset",
    siteId: "site-bali-lobby",
    code: "BS-M01",
    status: "available",
    batteryPct: 82,
    lat: -8.7178,
    lng: 115.1709,
  }),
  unit({
    id: "v-bw-01",
    modelId: "m-city-x1",
    operatorId: "op-beachwalk",
    siteId: "site-beach-hub",
    code: "BW-E01",
    status: "available",
    batteryPct: 85,
    lat: -8.6595,
    lng: 115.1303,
  }),
  unit({
    id: "v-bw-02",
    modelId: "m-canggu-moped",
    operatorId: "op-beachwalk",
    siteId: "site-beach-hub",
    code: "BW-M01",
    status: "available",
    batteryPct: 74,
    lat: -8.6596,
    lng: 115.1304,
  }),
  unit({
    id: "v-ub-01",
    modelId: "m-rice-terrace",
    operatorId: "op-ubud",
    siteId: "site-ubud-desk",
    code: "UB-L01",
    status: "available",
    batteryPct: null,
    lat: -8.5069,
    lng: 115.2625,
  }),
  unit({
    id: "v-ub-02",
    modelId: "m-temple-assist",
    operatorId: "op-ubud",
    siteId: "site-ubud-desk",
    code: "UB-E01",
    status: "available",
    batteryPct: 78,
    lat: -8.507,
    lng: 115.2626,
  }),
];


export function defaultPricingForHourly(baseHourly: number): PricingTier[] {
  return [
    { label: "30 min", durationMinutes: 30, priceIdr: Math.round(baseHourly * 0.6) },
    { label: "1 Hour", durationMinutes: 60, priceIdr: baseHourly },
    { label: "2 Hours", durationMinutes: 120, priceIdr: Math.round(baseHourly * 1.8) },
    { label: "3 Hours", durationMinutes: 180, priceIdr: Math.round(baseHourly * 2.4) },
    { label: "6 Hours", durationMinutes: 360, priceIdr: Math.round(baseHourly * 4) },
    { label: "12 Hours", durationMinutes: 720, priceIdr: Math.round(baseHourly * 7) },
    { label: "1 Day", durationMinutes: 1440, priceIdr: Math.round(baseHourly * 7) },
    { label: "2 Days", durationMinutes: 2880, priceIdr: Math.round(baseHourly * 13) },
    { label: "3 Days", durationMinutes: 4320, priceIdr: Math.round(baseHourly * 18) },
    { label: "1 Week", durationMinutes: 10080, priceIdr: Math.round(baseHourly * 36) },
  ];
}

export const operatorPricing: Record<string, PricingTier[]> = {
  "op-margonda": defaultPricingForHourly(35_000),
  "op-tebet": defaultPricingForHourly(32_000),
  "op-rawamangun": defaultPricingForHourly(30_000),
  "op-bali-sunset": defaultPricingForHourly(50_000),
  "op-beachwalk": defaultPricingForHourly(40_000),
  "op-ubud": defaultPricingForHourly(35_000),
};

export const staff: StaffMember[] = [
  {
    id: "st-rina",
    operatorId: "op-margonda",
    name: "Rina Admin",
    role: "admin",
    siteIds: null,
    username: "margonda.admin",
    password: "casan2026",
    online: true,
    locationLabel: "All Margonda sites",
  },
  {
    id: "st-andi",
    operatorId: "op-tebet",
    name: "Andi Booking",
    role: "booking_manager",
    siteIds: ["site-tebet-desk"],
    username: "tebet.admin",
    password: "casan2026",
    online: true,
    locationLabel: "Tebet desk",
  },
  {
    id: "st-sari",
    operatorId: "op-rawamangun",
    name: "Sari Fleet",
    role: "fleet_attendant",
    siteIds: ["site-rawa-counter"],
    username: "rawa.fleet",
    password: "casan2026",
    online: true,
    locationLabel: "Rawamangun",
  },
  {
    id: "st-wayan",
    operatorId: "op-bali-sunset",
    name: "Wayan Admin",
    role: "admin",
    siteIds: null,
    username: "balisunset.admin",
    password: "casan2026",
    online: true,
    locationLabel: "All locations",
  },
  {
    id: "st-made",
    operatorId: "op-bali-sunset",
    name: "Made Kusuma",
    role: "booking_manager",
    siteIds: ["site-bali-lobby"],
    username: "made.booking",
    password: "casan2026",
    online: true,
    locationLabel: "Bali Sunset",
  },
  {
    id: "st-dewi",
    operatorId: "op-beachwalk",
    name: "Dewi Sari",
    role: "fleet_attendant",
    siteIds: ["site-beach-hub"],
    username: "beachwalk.fleet",
    password: "casan2026",
    online: false,
    locationLabel: "BeachWalk",
  },
  {
    id: "st-nyoman",
    operatorId: "op-ubud",
    name: "Nyoman Ari",
    role: "viewer",
    siteIds: ["site-ubud-desk"],
    username: "ubud.view",
    password: "casan2026",
    online: false,
    locationLabel: "Ubud Center",
  },
];

const REVIEW_NOTES = [
  "Perfect for kost life — charged overnight with the 2A adapter.",
  "Casan voucher worked at the Margonda hub. Easy redeem.",
  "Battery lasting campus ↔ kost no problem.",
  "Staff explained 48V vs 60V clearly. Felt safe.",
  "Self-collect QR was fast after class.",
  "Wish I had taken the 3-pack voucher earlier.",
  "Moped was clean; 72V pack still had juice after Depok run.",
  "Lobby pickup under 5 minutes.",
  "Adapter deposit returned without drama.",
  "Maps match the real kost alley — nice.",
  "Great for weekly commute. Will renew.",
  "5A adapter tripped our kost breaker — switched to Casan hub.",
  "Friendly counter, English + Bahasa ok.",
  "Unit code matched the app. Smooth.",
  "Range estimate was accurate for my ride.",
];

const REVIEW_NAMES = [
  "Alya P.",
  "Bima K.",
  "Citra S.",
  "Dimas R.",
  "Eka W.",
  "Fajar N.",
  "Gita L.",
  "Hendra T.",
  "Indah M.",
  "Joko A.",
  "Kirana D.",
  "Luthfi Z.",
  "Maya U.",
  "Nadya F.",
  "Omar H.",
  "Putri V.",
  "Rafi J.",
  "Salsa Q.",
  "Tyo B.",
  "Uli C.",
  "Vina E.",
  "Wira G.",
  "Yuni I.",
  "Zaki O.",
  "Nina P.",
];

function bulkReviews(
  operatorId: string,
  models: string[],
  count: number,
  seedOffset: number,
): OperatorReview[] {
  const out: OperatorReview[] = [];
  for (let i = 0; i < count; i++) {
    const day = 15 - (i % 14);
    const rating = ([5, 5, 5, 4, 4, 3, 5, 4] as const)[i % 8];
    out.push({
      id: `rv-${operatorId}-${i + 1}`,
      operatorId,
      riderName: REVIEW_NAMES[(i + seedOffset) % REVIEW_NAMES.length],
      rating,
      note: REVIEW_NOTES[(i + seedOffset) % REVIEW_NOTES.length],
      modelName: models[i % models.length],
      createdAt: `2026-07-${String(Math.max(1, day)).padStart(2, "0")}T${String(8 + (i % 10)).padStart(2, "0")}:${String((i * 7) % 60).padStart(2, "0")}:00.000Z`,
    });
  }
  return out;
}

export const seedReviews: OperatorReview[] = [
  ...bulkReviews(
    "op-margonda",
    ["Ofero Galaxy 3 Lit", "Ofero Ledo 3 Lit", "Uwinfly M110G"],
    32,
    0,
  ),
  ...bulkReviews(
    "op-tebet",
    ["Ofero Magical 3 Lit", "Ofero Stareer 3 Lit"],
    28,
    3,
  ),
  ...bulkReviews(
    "op-rawamangun",
    ["Uwinfly City Ride", "Ofero Picassio"],
    24,
    7,
  ),
  {
    id: "rv1",
    operatorId: "op-bali-sunset",
    riderName: "Sophie M.",
    rating: 5,
    note: "Easy desk pickup, bikes were clean and charged.",
    modelName: "Ofero Galaxy 3 Lit",
    createdAt: "2026-07-10T09:00:00.000Z",
  },
  {
    id: "rv2",
    operatorId: "op-bali-sunset",
    riderName: "Kenji T.",
    rating: 4,
    note: "Self-collect at Lot B worked — no one needed.",
    modelName: "Uwinfly M110G",
    createdAt: "2026-07-08T14:20:00.000Z",
  },
  {
    id: "rv3",
    operatorId: "op-beachwalk",
    riderName: "Amelia R.",
    rating: 5,
    note: "Unlocked at the pin in 30 seconds. Great for Canggu.",
    modelName: "Ofero Magical 3 Lit",
    createdAt: "2026-07-12T11:00:00.000Z",
  },
  {
    id: "rv4",
    operatorId: "op-beachwalk",
    riderName: "Luis G.",
    rating: 4,
    note: "Moped battery lasted all afternoon.",
    modelName: "Ofero Stareer 3 Lit",
    createdAt: "2026-07-05T16:40:00.000Z",
  },
  {
    id: "rv5",
    operatorId: "op-ubud",
    riderName: "Priya S.",
    rating: 5,
    note: "Friendly counter staff, perfect for rice terraces.",
    modelName: "Uwinfly City Ride",
    createdAt: "2026-07-09T08:15:00.000Z",
  },
];

export const seedNotifications: AppNotification[] = [
  {
    id: "n1",
    title: "Welcome to Casan Rent",
    body: "Jakarta kost rentals — see battery V/Ah, add Casan vouchers or adapters.",
    read: false,
    createdAt: new Date().toISOString(),
    href: "/home",
  },
  {
    id: "n2",
    title: "Demo payments",
    body: "QRIS and e-wallet checkout is mocked for this build.",
    read: false,
    createdAt: new Date().toISOString(),
    href: "/home",
  },
  {
    id: "n3",
    title: "What's New v0.4",
    body: "Jakarta hubs, OSM maps, charging add-ons, review pagination.",
    read: false,
    createdAt: new Date().toISOString(),
    href: "/updates",
  },
];

/** Past paid trips so Earnings / Home money look real for demo. */
function mockPaid(
  partial: Omit<
    Booking,
    | "addons"
    | "addonsPriceIdr"
    | "depositIdr"
    | "motorOn"
    | "rating"
    | "reviewNote"
    | "paymentStatus"
    | "paymentMethod"
    | "startsAt"
    | "endsAt"
    | "createdAt"
    | "physicalKeyGiven"
    | "physicalKeyReturned"
    | "digitalKeyIssueMode"
    | "digitalKeyIssuedAt"
    | "returnSiteId"
  > & {
    hoursAgo: number;
    digitalKeyIssueMode?: Booking["digitalKeyIssueMode"];
    digitalKeyIssuedAt?: string | null;
    returnSiteId?: string;
  },
): Booking {
  const created = new Date(Date.now() - partial.hoursAgo * 3600_000).toISOString();
  const { hoursAgo: _, ...rest } = partial;
  const needsPhys =
    rest.keysAccess === "physical" || rest.keysAccess === "both";
  return {
    ...rest,
    createdAt: created,
    startsAt: created,
    endsAt: created,
    addons: [],
    addonsPriceIdr: 0,
    depositIdr: DEPOSIT_IDR,
    motorOn: false,
    rating: 5,
    reviewNote: "Demo ride",
    paymentStatus: "paid",
    paymentMethod: "qris",
    physicalKeyGiven: needsPhys,
    physicalKeyReturned: needsPhys,
    riderPhone: rest.riderPhone ?? "+62 812-0000-0000",
    returnSiteId: rest.returnSiteId ?? rest.siteId,
    digitalKeyIssueMode: rest.digitalKeyIssueMode ?? "auto",
    digitalKeyIssuedAt:
      rest.digitalKeyIssuedAt ??
      (rest.keysAccess === "digital" || rest.keysAccess === "both"
        ? created
        : null),
  };
}

export const seedMockBookings: Booking[] = [
  mockPaid({
    id: "bk-mock-1",
    code: "CR-DEMO01",
    operatorId: "op-margonda",
    vehicleId: "v-mg-g1",
    modelId: "m-margo-galaxy",
    siteId: "site-margonda-lobby",
    riderName: "Alya (student)",
    status: "completed",
    pickupType: "front_desk",
    rentalMode: "digital",
    keysAccess: "both",
    durationLabel: "1 Day",
    durationMinutes: 1440,
    rentalPriceIdr: 245_000,
    hoursAgo: 5,
  }),
  mockPaid({
    id: "bk-mock-2",
    code: "CR-DEMO02",
    operatorId: "op-margonda",
    vehicleId: "v-mg-l1",
    modelId: "m-margo-ledo",
    siteId: "site-jakarta-tebet",
    riderName: "Bima K.",
    status: "completed",
    pickupType: "front_desk",
    rentalMode: "key_handover",
    keysAccess: "physical",
    durationLabel: "3 Hours",
    durationMinutes: 180,
    rentalPriceIdr: 45_000,
    hoursAgo: 28,
  }),
  mockPaid({
    id: "bk-mock-3",
    code: "CR-DEMO03",
    operatorId: "op-margonda",
    vehicleId: "v-mg-m1",
    modelId: "m-margo-m110",
    siteId: "site-margonda-lobby",
    riderName: "Citra S.",
    status: "completed",
    pickupType: "front_desk",
    rentalMode: "digital",
    keysAccess: "both",
    durationLabel: "1 Week",
    durationMinutes: 10080,
    rentalPriceIdr: 1_260_000,
    hoursAgo: 50,
  }),
  mockPaid({
    id: "bk-mock-4",
    code: "CR-DEMO04",
    operatorId: "op-tebet",
    vehicleId: "v-tb-m1",
    modelId: "m-tebet-magical",
    siteId: "site-tebet-desk",
    riderName: "Dimas R.",
    status: "completed",
    pickupType: "front_desk",
    rentalMode: "key_handover",
    keysAccess: "physical",
    durationLabel: "6 Hours",
    durationMinutes: 360,
    rentalPriceIdr: 72_000,
    hoursAgo: 12,
  }),
  mockPaid({
    id: "bk-mock-5",
    code: "CR-DEMO05",
    operatorId: "op-tebet",
    vehicleId: "v-tb-s1",
    modelId: "m-tebet-stareer",
    siteId: "site-tebet-desk",
    riderName: "Eka W.",
    status: "completed",
    pickupType: "front_desk",
    rentalMode: "digital",
    keysAccess: "both",
    durationLabel: "2 Days",
    durationMinutes: 2880,
    rentalPriceIdr: 715_000,
    hoursAgo: 72,
  }),
  mockPaid({
    id: "bk-mock-6",
    code: "CR-DEMO06",
    operatorId: "op-rawamangun",
    vehicleId: "v-rw-c1",
    modelId: "m-rawa-city",
    siteId: "site-rawa-counter",
    riderName: "Fajar N.",
    status: "completed",
    pickupType: "front_desk",
    rentalMode: "key_handover",
    keysAccess: "physical",
    durationLabel: "1 Day",
    durationMinutes: 1440,
    rentalPriceIdr: 70_000,
    hoursAgo: 8,
  }),
  mockPaid({
    id: "bk-mock-7",
    code: "CR-DEMO07",
    operatorId: "op-bali-sunset",
    vehicleId: "v-bs-01",
    modelId: "m-eco-cruiser",
    siteId: "site-bali-lobby",
    riderName: "Guest Tourist",
    status: "completed",
    pickupType: "front_desk",
    rentalMode: "digital",
    keysAccess: "both",
    durationLabel: "1 Day",
    durationMinutes: 1440,
    rentalPriceIdr: 350_000,
    hoursAgo: 20,
  }),
  // Live demo trips: one ride in progress + one paid booking ready to collect,
  // so Home banners and Trips → Ongoing show every rider state out of the box.
  {
    id: "bk-mock-active",
    code: "CR-RIDE01",
    operatorId: "op-margonda",
    vehicleId: "v-mg-e2",
    modelId: "m-margo-galaxy",
    siteId: "site-margonda-lobby",
    riderName: "You (demo)",
    riderPhone: "+62 812-0000-0000",
    status: "active",
    pickupType: "front_desk",
    rentalMode: "digital",
    keysAccess: "both",
    physicalKeyGiven: true,
    physicalKeyReturned: false,
    digitalKeyIssueMode: "auto",
    digitalKeyIssuedAt: new Date(Date.now() - 40 * 60_000).toISOString(),
    returnSiteId: "site-margonda-lobby",
    durationLabel: "2 Hours",
    durationMinutes: 120,
    rentalPriceIdr: 63_000,
    addonsPriceIdr: 0,
    addons: [],
    depositIdr: DEPOSIT_IDR,
    paymentMethod: "qris",
    paymentStatus: "paid",
    appointmentAt: null,
    readyAt: new Date(Date.now() - 40 * 60_000).toISOString(),
    startsAt: new Date(Date.now() - 25 * 60_000).toISOString(),
    endsAt: new Date(Date.now() + 95 * 60_000).toISOString(),
    completedAt: null,
    extensions: [],
    motorOn: true,
    createdAt: new Date(Date.now() - 50 * 60_000).toISOString(),
    rating: null,
    reviewNote: null,
  },
  {
    id: "bk-mock-ready",
    code: "CR-READY1",
    operatorId: "op-margonda",
    vehicleId: "v-mg-m2",
    modelId: "m-margo-m110",
    siteId: "site-margonda-lobby",
    riderName: "You (demo)",
    riderPhone: "+62 812-0000-0000",
    status: "awaiting_pickup",
    pickupType: "front_desk",
    rentalMode: "digital",
    keysAccess: "both",
    physicalKeyGiven: false,
    physicalKeyReturned: false,
    digitalKeyIssueMode: "auto",
    digitalKeyIssuedAt: new Date(Date.now() - 5 * 60_000).toISOString(),
    returnSiteId: "site-margonda-lobby",
    durationLabel: "6 Hours",
    durationMinutes: 360,
    rentalPriceIdr: 330_000,
    addonsPriceIdr: 0,
    addons: [],
    depositIdr: DEPOSIT_IDR,
    paymentMethod: "qris",
    paymentStatus: "paid",
    appointmentAt: new Date(Date.now() + 20 * 60_000).toISOString(),
    readyAt: new Date(Date.now() - 2 * 60_000).toISOString(),
    startsAt: null,
    endsAt: null,
    completedAt: null,
    extensions: [],
    motorOn: false,
    createdAt: new Date(Date.now() - 30 * 60_000).toISOString(),
    rating: null,
    reviewNote: null,
  },
  {
    id: "bk-mock-waiting",
    code: "CR-WAIT01",
    operatorId: "op-margonda",
    vehicleId: "v-mg-e3",
    modelId: "m-margo-galaxy",
    siteId: "site-margonda-lobby",
    riderName: "You (demo)",
    riderPhone: "+62 812-0000-0000",
    status: "pending",
    pickupType: "front_desk",
    rentalMode: "digital",
    keysAccess: "both",
    physicalKeyGiven: false,
    physicalKeyReturned: false,
    digitalKeyIssueMode: "auto",
    digitalKeyIssuedAt: null,
    returnSiteId: "site-margonda-lobby",
    durationLabel: "3 Hours",
    durationMinutes: 180,
    rentalPriceIdr: 95_000,
    addonsPriceIdr: 0,
    addons: [],
    depositIdr: DEPOSIT_IDR,
    paymentMethod: "casan_wallet",
    paymentStatus: "paid",
    appointmentAt: new Date(Date.now() + 90 * 60_000).toISOString(),
    readyAt: null,
    startsAt: null,
    endsAt: null,
    completedAt: null,
    extensions: [],
    motorOn: false,
    createdAt: new Date(Date.now() - 12 * 60_000).toISOString(),
    rating: null,
    reviewNote: null,
  },
  {
    id: "bk-mock-unpaid",
    code: "CR-PAY01",
    operatorId: "op-margonda",
    vehicleId: "v-mg-e4",
    modelId: "m-margo-galaxy",
    siteId: "site-margonda-lobby",
    riderName: "You (demo)",
    riderPhone: "+62 812-0000-0000",
    status: "pending",
    pickupType: "self_service",
    rentalMode: "digital",
    keysAccess: "digital",
    physicalKeyGiven: false,
    physicalKeyReturned: false,
    digitalKeyIssueMode: "auto",
    digitalKeyIssuedAt: null,
    returnSiteId: "site-margonda-lobby",
    durationLabel: "1 Hour",
    durationMinutes: 60,
    rentalPriceIdr: 35_000,
    addonsPriceIdr: 0,
    addons: [],
    depositIdr: DEPOSIT_IDR,
    paymentMethod: "casan_wallet",
    paymentStatus: "pending",
    appointmentAt: new Date(Date.now() + 45 * 60_000).toISOString(),
    readyAt: null,
    startsAt: null,
    endsAt: null,
    completedAt: null,
    extensions: [],
    motorOn: false,
    createdAt: new Date(Date.now() - 8 * 60_000).toISOString(),
    rating: null,
    reviewNote: null,
  },
];
