import type {
  Operator,
  PricingTier,
  StaffMember,
  Vehicle,
  AppNotification,
} from "./types";

export const DEPOSIT_IDR = 200_000;

export const operators: Operator[] = [
  {
    id: "op-bali-sunset",
    slug: "bali-sunset",
    name: "Bali Sunset Hotel",
    address: "Jl. Pantai Kuta No. 42, Kuta",
    city: "Bali",
    lat: -8.7177,
    lng: 115.1708,
    hours: "07:00 - 20:00",
    phone: "+62 812-3456-7890",
    email: "rental@balisunset.com",
    supportsFrontDesk: true,
    supportsSelfService: true,
    platformFeePct: 20,
    emoji: "🏨",
  },
  {
    id: "op-beachwalk",
    slug: "beachwalk",
    name: "BeachWalk Rental Hub",
    address: "Jl. Pantai Berawa, Canggu",
    city: "Bali",
    lat: -8.6595,
    lng: 115.1303,
    hours: "06:30 - 21:00",
    phone: "+62 812-2222-3333",
    email: "hello@beachwalk.id",
    supportsFrontDesk: false,
    supportsSelfService: true,
    platformFeePct: 18,
    emoji: "🏛",
  },
  {
    id: "op-ubud",
    slug: "ubud-center",
    name: "Ubud Tourism Center",
    address: "Jl. Raya Ubud No. 18",
    city: "Bali",
    lat: -8.5069,
    lng: 115.2625,
    hours: "08:00 - 18:00",
    phone: "+62 812-8888-1111",
    email: "desk@ubudcenter.id",
    supportsFrontDesk: true,
    supportsSelfService: false,
    platformFeePct: 22,
    emoji: "🏫",
  },
];

export const vehicles: Vehicle[] = [
  {
    id: "v-eco-cruiser",
    operatorId: "op-bali-sunset",
    code: "BSH-E01",
    name: "Eco Cruiser Pro",
    vehicleType: "ebike",
    status: "available",
    rentalMode: "both",
    allowFrontDesk: true,
    allowSelfService: true,
    batteryPct: 85,
    motorWatts: 250,
    rangeKm: 60,
    maxSpeedKmh: 25,
    weightKg: 22,
    pricePerHour: 50_000,
    lat: -8.7177,
    lng: 115.1708,
    emoji: "🚲",
    requiresSimAck: false,
  },
  {
    id: "v-city-x1",
    operatorId: "op-beachwalk",
    code: "BW-E12",
    name: "City Explorer X1",
    vehicleType: "ebike",
    status: "available",
    rentalMode: "digital",
    allowFrontDesk: false,
    allowSelfService: true,
    batteryPct: 62,
    motorWatts: 350,
    rangeKm: 80,
    maxSpeedKmh: 28,
    weightKg: 24,
    pricePerHour: 40_000,
    lat: -8.6595,
    lng: 115.1303,
    emoji: "🚴",
    requiresSimAck: false,
  },
  {
    id: "v-beach-lite",
    operatorId: "op-beachwalk",
    code: "BW-K03",
    name: "Beach Rider Lite",
    vehicleType: "bicycle",
    status: "available",
    rentalMode: "key_handover",
    allowFrontDesk: false,
    allowSelfService: true,
    batteryPct: null,
    motorWatts: null,
    rangeKm: null,
    maxSpeedKmh: null,
    weightKg: 14,
    pricePerHour: 35_000,
    lat: -8.6595,
    lng: 115.1303,
    emoji: "🚲",
    requiresSimAck: false,
  },
  {
    id: "v-trail-bike",
    operatorId: "op-ubud",
    code: "UB-B02",
    name: "Rice Terrace Cruiser",
    vehicleType: "bicycle",
    status: "available",
    rentalMode: "key_handover",
    allowFrontDesk: true,
    allowSelfService: false,
    batteryPct: null,
    motorWatts: null,
    rangeKm: null,
    maxSpeedKmh: null,
    weightKg: 13,
    pricePerHour: 30_000,
    lat: -8.5069,
    lng: 115.2625,
    emoji: "🚲",
    requiresSimAck: false,
  },
  {
    id: "v-swift-moped",
    operatorId: "op-bali-sunset",
    code: "BSH-M07",
    name: "Swift E-Moped S7",
    vehicleType: "emoped",
    status: "available",
    rentalMode: "both",
    allowFrontDesk: true,
    allowSelfService: true,
    batteryPct: 91,
    motorWatts: 1500,
    rangeKm: 70,
    maxSpeedKmh: 45,
    weightKg: 68,
    pricePerHour: 75_000,
    lat: -8.7178,
    lng: 115.171,
    emoji: "🛵",
    requiresSimAck: true,
  },
  {
    id: "v-canggu-moped",
    operatorId: "op-beachwalk",
    code: "BW-M01",
    name: "Canggu Glide Moped",
    vehicleType: "emoped",
    status: "available",
    rentalMode: "digital",
    allowFrontDesk: false,
    allowSelfService: true,
    batteryPct: 74,
    motorWatts: 1200,
    rangeKm: 55,
    maxSpeedKmh: 42,
    weightKg: 65,
    pricePerHour: 65_000,
    lat: -8.6596,
    lng: 115.1305,
    emoji: "🛵",
    requiresSimAck: true,
  },
  {
    id: "v-ubud-assist",
    operatorId: "op-ubud",
    code: "UB-E04",
    name: "Temple Path Assist",
    vehicleType: "ebike",
    status: "available",
    rentalMode: "key_handover",
    allowFrontDesk: true,
    allowSelfService: false,
    batteryPct: 78,
    motorWatts: 250,
    rangeKm: 50,
    maxSpeedKmh: 25,
    weightKg: 21,
    pricePerHour: 45_000,
    lat: -8.507,
    lng: 115.2626,
    emoji: "🚴",
    requiresSimAck: false,
  },
  {
    id: "v-maint",
    operatorId: "op-bali-sunset",
    code: "BSH-E09",
    name: "Workshop Spare",
    vehicleType: "ebike",
    status: "maintenance",
    rentalMode: "digital",
    allowFrontDesk: true,
    allowSelfService: true,
    batteryPct: 12,
    motorWatts: 250,
    rangeKm: 60,
    maxSpeedKmh: 25,
    weightKg: 22,
    pricePerHour: 50_000,
    lat: -8.7175,
    lng: 115.1705,
    emoji: "🚲",
    requiresSimAck: false,
  },
];

export function defaultPricingForHourly(baseHourly: number): PricingTier[] {
  return [
    { label: "30 min", durationMinutes: 30, priceIdr: Math.round(baseHourly * 0.6) },
    { label: "1 Hour", durationMinutes: 60, priceIdr: baseHourly },
    { label: "2 Hours", durationMinutes: 120, priceIdr: Math.round(baseHourly * 1.8) },
    { label: "3 Hours", durationMinutes: 180, priceIdr: Math.round(baseHourly * 2.4) },
    { label: "6 Hours", durationMinutes: 360, priceIdr: Math.round(baseHourly * 4) },
    { label: "12 Hours", durationMinutes: 720, priceIdr: Math.round(baseHourly * 7) },
    { label: "1 Day", durationMinutes: 1440, priceIdr: Math.round(baseHourly * 7) },
    { label: "2 Days", durationMinutes: 2880, priceIdr: Math.round(baseHourly * 13) },
    { label: "3 Days", durationMinutes: 4320, priceIdr: Math.round(baseHourly * 18) },
    { label: "1 Week", durationMinutes: 10080, priceIdr: Math.round(baseHourly * 36) },
  ];
}

export const operatorPricing: Record<string, PricingTier[]> = {
  "op-bali-sunset": defaultPricingForHourly(50_000),
  "op-beachwalk": defaultPricingForHourly(40_000),
  "op-ubud": defaultPricingForHourly(35_000),
};

export const staff: StaffMember[] = [
  {
    id: "st-wayan",
    operatorId: "op-bali-sunset",
    name: "Wayan Admin",
    role: "admin",
    username: "balisunset.admin",
    password: "casan2026",
    online: true,
    locationLabel: "All locations",
  },
  {
    id: "st-made",
    operatorId: "op-bali-sunset",
    name: "Made Kusuma",
    role: "booking_manager",
    username: "made.booking",
    password: "casan2026",
    online: true,
    locationLabel: "Bali Sunset",
  },
  {
    id: "st-dewi",
    operatorId: "op-beachwalk",
    name: "Dewi Sari",
    role: "fleet_attendant",
    username: "beachwalk.fleet",
    password: "casan2026",
    online: false,
    locationLabel: "BeachWalk",
  },
  {
    id: "st-nyoman",
    operatorId: "op-ubud",
    name: "Nyoman Ari",
    role: "viewer",
    username: "ubud.view",
    password: "casan2026",
    online: false,
    locationLabel: "Ubud Center",
  },
];

export const seedNotifications: AppNotification[] = [
  {
    id: "n1",
    title: "Welcome to Casan Rent",
    body: "Book bikes, e-bikes, and e-mopeds from multiple operators.",
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "n2",
    title: "Demo payments",
    body: "QRIS and e-wallet checkout is mocked for this build.",
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "n3",
    title: "IoT unlock is mocked",
    body: "Motor and immobilizer commands call /api/iot.",
    read: false,
    createdAt: new Date().toISOString(),
  },
];
